Repository Week12-13-GOAT/pintos-vm, pull requests merged in 2025-06, with the labels that each got.

#23 [FEAT]: 공통 파일 구조체(in vm)
  pintos-kaist/include/vm/file.h
Labels: add

#25 anon swap in/out (추가 구현이 필요함)
  pintos-kaist/vm/anon.c
Labels: add

#26 [Fix] spt_copy 수정
  pintos-kaist/vm/vm.c
Labels: enhancement

#27 mmap 테스트 일부와 fork-read 해결
  pintos-kaist/include/vm/vm.h
  pintos-kaist/userprog/process.c
  pintos-kaist/vm/file.c
  pintos-kaist/vm/vm.c
Labels: enhancement

#28 [FEAT] file swap in/out 구현
  pintos-kaist/vm/file.c
Labels: add

#33 mmap 테스트 모두 통과 !!
  pintos-kaist/userprog/process.c
  pintos-kaist/vm/uninit.c
  pintos-kaist/vm/vm.c
Labels: enhancement

#39 [Comment] : anon swap in/out, destroy
  pintos-kaist/vm/anon.c
Labels: documentation

#40 test all pass
  pintos-kaist/include/vm/vm.h
  pintos-kaist/userprog/exception.c
  pintos-kaist/userprog/process.c
  pintos-kaist/userprog/syscall.c
  pintos-kaist/vm/anon.c
  pintos-kaist/vm/file.c
  pintos-kaist/vm/vm.c
Labels: enhancement

#43 anon page 주석 달기 (공부용)
  pintos-kaist/userprog/process.c
  pintos-kaist/vm/anon.c
  pintos-kaist/vm/uninit.c
  pintos-kaist/vm/vm.c
Labels: Comment

#44 주석 심화 과정 보고 틀린거 있으면 검수좀
  pintos-kaist/include/vm/vm.h
  pintos-kaist/userprog/syscall.c
  pintos-kaist/vm/file.c
Labels: Comment
